# Generated by Django 5.1.4 on 2025-04-23 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_customuser_is_artist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_artist',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='location',
        ),
    ]
