# Generated by Django 5.2 on 2025-04-23 13:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_customuser_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='events',
            field=models.ManyToManyField(blank=True, related_name='event_artists', to='api.event'),
        ),
        migrations.AddField(
            model_name='event',
            name='artists',
            field=models.ManyToManyField(blank=True, related_name='event_artists', to='api.artist'),
        ),
        migrations.AlterField(
            model_name='artistreview',
            name='rating',
            field=models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='eventreview',
            name='rating',
            field=models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
