# Generated by Django 5.1.4 on 2025-04-23 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='website',
        ),
    ]
