# Generated by Django 5.1.4 on 2025-04-23 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_remove_customuser_website'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventreview',
            name='event',
        ),
        migrations.RemoveField(
            model_name='eventreview',
            name='user',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='events',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='reset_token',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='user_type',
        ),
        migrations.RemoveField(
            model_name='event',
            name='artists',
        ),
        migrations.RemoveField(
            model_name='event',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='event',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='event',
            name='status',
        ),
        migrations.RemoveField(
            model_name='eventorganizer',
            name='is_verified',
        ),
        migrations.AddField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_artist',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(default='0000000000', max_length=20),
        ),
        migrations.AlterField(
            model_name='tickettype',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='api.event'),
        ),
        migrations.DeleteModel(
            name='ArtistReview',
        ),
        migrations.DeleteModel(
            name='EventReview',
        ),
    ]
