# Generated by Django 5.1.4 on 2025-04-23 23:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_customuser_token_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='events',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='token_created_at',
        ),
        migrations.RemoveField(
            model_name='event',
            name='artists',
        ),
        migrations.RemoveField(
            model_name='event',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='event',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='event',
            name='status',
        ),
        migrations.RemoveField(
            model_name='eventorganizer',
            name='is_verified',
        ),
        migrations.AlterField(
            model_name='artistreview',
            name='comment',
            field=models.TextField(default='No comment'),
        ),
        migrations.AlterField(
            model_name='artistreview',
            name='rating',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='artistreview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artist_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='eventreview',
            name='comment',
            field=models.TextField(default='No comment'),
        ),
        migrations.AlterField(
            model_name='eventreview',
            name='rating',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='eventreview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tickettype',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='api.event'),
        ),
    ]
