# Generated by Django 5.1.4 on 2025-05-01 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_remove_customuser_artist_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='full_name',
        ),
    ]
