# Generated by Django 5.1.4 on 2025-05-07 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_alter_customuser_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='price',
            field=models.DecimalField(decimal_places=2, default=10000, max_digits=10),
            preserve_default=False,
        ),
    ]
