# Generated by Django 5.2 on 2025-04-16 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_bannerdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('artist_name', models.CharField(max_length=255)),
                ('review', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(upload_to='music_images/')),
                ('link', models.URLField()),
                ('artists', models.ManyToManyField(related_name='music', to='api.artist')),
            ],
        ),
    ]
