# Generated by Django 5.1.4 on 2025-04-22 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_ticketcategory_tickettype_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_artist',
            field=models.BooleanField(default=False),
        ),
    ]
