# Generated by Django 5.0.1 on 2025-04-07 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dans',
            fields=[
                ('данс_id', models.AutoField(primary_key=True, serialize=False)),
                ('данс_дугаар', models.CharField(max_length=20, unique=True)),
                ('пин_код', models.CharField(max_length=6)),
                ('дансны_төрөл', models.CharField(choices=[('SAVINGS', 'Хадгаламж'), ('CURRENT', 'Харилцах')], max_length=50)),
                ('үлдэгдэл', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('валют', models.CharField(max_length=10)),
                ('үүсгэсэн_огноо', models.DateTimeField(auto_now_add=True)),
                ('шинэчлэгдсэн_огноо', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='KioskDevice',
            fields=[
                ('киоск_id', models.AutoField(primary_key=True, serialize=False)),
                ('байршил', models.CharField(max_length=255)),
                ('төлөв', models.CharField(max_length=20)),
                ('дэмжигдсэн_валют', models.TextField()),
                ('сүүлийн_засвар', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('овог', models.CharField(max_length=100)),
                ('нэр', models.CharField(max_length=100)),
                ('утас', models.CharField(max_length=15)),
                ('имэйл', models.EmailField(max_length=255)),
                ('бүртгэсэн_огноо', models.DateTimeField(auto_now_add=True)),
                ('шинэчлэгдсэн_огноо', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Guilgee',
            fields=[
                ('гүйлгээ_id', models.AutoField(primary_key=True, serialize=False)),
                ('гүйлгээний_төрөл', models.CharField(choices=[('TRANSFER', 'Шилжүүлэг'), ('PAYMENT', 'Төлбөр')], max_length=50)),
                ('дүн', models.DecimalField(decimal_places=2, max_digits=18)),
                ('валют', models.CharField(max_length=10)),
                ('гүйлгээний_огноо', models.DateTimeField(auto_now_add=True)),
                ('төлөв', models.CharField(choices=[('PENDING', 'Хүлээгдэж буй'), ('COMPLETED', 'Дууссан'), ('FAILED', 'Амжилтгүй')], default='PENDING', max_length=20)),
                ('account_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shiljuulegch', to='kioskapp.dans')),
                ('account_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='huleen_awagch', to='kioskapp.dans')),
            ],
        ),
        migrations.CreateModel(
            name='Huraamj',
            fields=[
                ('хураамжid', models.AutoField(primary_key=True, serialize=False)),
                ('хураамж_төрөл', models.CharField(choices=[('TRANSFER_FEE', 'Шилжүүлгийн хураамж'), ('PAYMENT_FEE', 'Төлбөрийн хураамж')], max_length=50)),
                ('хураамж_дүн', models.DecimalField(decimal_places=2, max_digits=18)),
                ('валют', models.CharField(max_length=10)),
                ('төлөв', models.CharField(choices=[('PENDING', 'Хүлээгдэж буй'), ('PAID', 'Төлөгдсөн')], default='PENDING', max_length=20)),
                ('гүйлгээ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='kioskapp.guilgee')),
            ],
        ),
        migrations.CreateModel(
            name='TulburiinMedeelel',
            fields=[
                ('төлбөрМэд_id', models.AutoField(primary_key=True, serialize=False)),
                ('төлбөрийн_төрөл', models.CharField(max_length=50)),
                ('дүн', models.DecimalField(decimal_places=2, max_digits=18)),
                ('төлөв', models.CharField(max_length=20)),
                ('төлбөр_хийгдсэн_огноо', models.DateTimeField(auto_now_add=True)),
                ('данс', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tulburiin_medeelel', to='kioskapp.dans')),
                ('хэрэглэгч', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tulburiin_medeelel', to='kioskapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='QRNfcPayment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('төлбөрийн_арга', models.CharField(max_length=20)),
                ('дүн', models.DecimalField(decimal_places=2, max_digits=18)),
                ('худалдааны_байгууллага', models.CharField(max_length=255)),
                ('төлөв', models.CharField(max_length=20)),
                ('гүйлгээний_огноо', models.DateTimeField(auto_now_add=True)),
                ('данс', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_nfc_payments', to='kioskapp.dans')),
                ('хэрэглэгч', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_nfc_payments', to='kioskapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='KioskSession',
            fields=[
                ('sessionid', models.AutoField(primary_key=True, serialize=False)),
                ('үйлдэл', models.CharField(max_length=255)),
                ('үйлдлийн_огноо', models.DateTimeField(auto_now_add=True)),
                ('төлөв', models.CharField(max_length=20)),
                ('киоск', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='kioskapp.kioskdevice')),
                ('хэрэглэгч', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kiosk_sessions', to='kioskapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Hadgalamj',
            fields=[
                ('хадгаламж_id', models.AutoField(primary_key=True, serialize=False)),
                ('хадгаламж_төрөл', models.CharField(max_length=50)),
                ('хувьцаа', models.DecimalField(decimal_places=2, max_digits=5)),
                ('эхлэх_огноо', models.DateTimeField(auto_now_add=True)),
                ('дуусах_огноо', models.DateTimeField()),
                ('төлөв', models.CharField(max_length=20)),
                ('данс', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savings', to='kioskapp.dans')),
                ('хэрэглэгч', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savings', to='kioskapp.user')),
            ],
        ),
        migrations.AddField(
            model_name='dans',
            name='хэрэглэгч',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dansnuud', to='kioskapp.user'),
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('картid', models.AutoField(primary_key=True, serialize=False)),
                ('карт_дугаар', models.CharField(max_length=16)),
                ('карт_төрөл', models.CharField(max_length=20)),
                ('дуусах_хугацаа', models.DateField()),
                ('пин_код', models.CharField(max_length=4)),
                ('төлөв', models.CharField(max_length=20)),
                ('данс', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='kioskapp.dans')),
                ('хэрэглэгч', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='kioskapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Zeel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('зээлийн_төрөл', models.CharField(max_length=50)),
                ('зээлийн_дүн', models.DecimalField(decimal_places=2, max_digits=18)),
                ('хувьцаа', models.DecimalField(decimal_places=2, max_digits=5)),
                ('төлөх_хугацаа', models.DateField()),
                ('төлөв', models.CharField(max_length=20)),
                ('данс', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='kioskapp.dans')),
                ('хэрэглэгч', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='kioskapp.user')),
            ],
        ),
    ]
